name: Deployment

on:
  push:
    branches:
      - 3-22-25-swaggerx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        uses: cham207388/github-custom-actions/mvn-jdk21@main

      - name: Destroy Lambda
        uses: cham207388/github-custom-actions/terraform@main
        with:
          directory: ./terraform
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          variables: "aws_region=us-east-2"
