name: CI

on:
  push:
    branches:
      - 2-gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check maven version
        run: |
          mvn --version

      - name: mvn clean
        run: mvn clean

      - name: mvn package
        run: mvn clean

      - name: check zip
        run: |
          ls -ltra