name: Teardown

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.4

      - name: Terraform Init
        run: |
            cd terraform
            terraform init -upgrade

      - name: Terraform Plan
        run: |
            cd terraform
            terraform plan

      - name: Terraform Destroy
        run: |
            cd terraform
            terraform destroy -auto-approve
