name: Teardown

on:
  workflow_dispatch:
  push:
    branches:
      - 3-22-25-swagger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        uses: ./.github/actions/build-project

      - name: Destroy Lambda
        uses: ./.github/actions/deploy
        with:
          directory: ./terraform
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          variables: "aws_region=us-east-2"
          destroy: 'yes'
