name: CI

on:
  push:
    branches:
      - 2-gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        uses: ./.github/actions/build-project

      - name: Deploy Lambda
        uses: ./.github/actions/deploy
        with:
          directory: ./terraform
          aws-region: us-east-2
          variables: "aws_region=us-east-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
